version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shab-app        
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shab-network 
  db:
    image: mysql:8.0
    container_name: shab-db            
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - shab-network  
  nginx:
    image: nginx:alpine
    container_name: nginx                 
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - shab-network  
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    depends_on:
        ['db']
    links:
        ['db:db']
    networks:
      - shab-network
networks:
  shab-network:
    driver: bridge
